### PR TITLE
Update mask.js

### PR DESCRIPTION
**Pull request by k-one-o-two**
This fixes a wired IE bug when pressing Ctrl+Z: IE doubles the input value.
Now the value is deleted (the behavior is copied from FireFox one).

### CODE REVIEW

**Comment by lukepfeiffer10** [comment]
Could you provide a test for this functionality? Also, your formatting commit looks a little goofy...

**Comment by k-one-o-two** [comment]
Sorry for the delay. Added a test (this actually is a copy on one in my project, so I'm not sure if it's ok for you).
Formatting - github's web editor is a bit strange.

**Comment by lukepfeiffer10** [comment]
So, it looks like your test is failing because you are trying to use jQuery which is not an included file for these tests. Could you please modify your test to not use jQuery?

**Comment by k-one-o-two** [comment]
I've changed the test. Don't really understand why it's failing - the same test works well for me.

**Comment by lukepfeiffer10** [comment]
Your test is failing in IE. Probably one of the `event` methods you are using is unsupported or conditionally supported... got to love IE...

**Comment by lukepfeiffer10** [comment]
I looked into the issue further and it looks like the problem is stemming from using `document.createEventObject` in conjunction with `el.dispatchEvent`.

`document.createEventObject` was apparently made to support IE's custom `fireEvent` function but the event object it creates does not play nicely with the `dispatchEvent` function. The problem is that IE 9 and 10 support `dispatchEvent` and `document.createEventObject` which is why your test is failing based on how you check for what functions to execute.

I tested it myself and you can remove the `document.createEventObject` code and the `fireEvent` code which simplifies things in your test too which is nice and it works in IE 9 and 10.

**Comment by k-one-o-two** [comment]
Thanks, the test is now passing

**Pull request merged**
