### PR TITLE
Added an escape character.

### PR DESCRIPTION
**Pull request by kevingill1966**
I added an escape character '\\' so that I can use the same value in the mask as the mask character,

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Can't you use `maskDefinitions` customization as describe there https://github.com/angular-ui/ui-mask#customizing ?

**Comment by PowerKiKi** [comment]
This lacks test and documentation to be meged

**Comment by lukepfeiffer10** [comment]
@kevingill1966 Have you looked at #32 and the related plunkr and PR #79? I think that might solve your issue.

**Comment by NDurham12** [comment]
@PowerKiKi, I'm trying to use the syntax you suggested as to not have to upgrade our version for the latest fix.  I finally got the ui-option working with ui-options='{ maskDefinitions : { "d": "/\d/" } }' to make 'd' the key, however (as the initial help explains) the setting is appended to the default list, so the 9 remains a valid key as well.  Outside of setting the uiMaskConfig.maskDefinitions on run, is there any other work around to clear out the defaults for a single use case for an application?

**Comment by PowerKiKi** [comment]
@NDurham12 you should be able to unset the predefined mask by setting them to `undefined` as described there: https://github.com/angular-ui/ui-mask/issues/72#issuecomment-169045244

**Comment by isaacplmann** [comment]
This feature is more powerful than just disabling a default mask definition.  Sometimes you want a character to appear in the mask even though it is being used as a definition key.

**Comment by lukepfeiffer10** [comment]
Closing this with the merge of #139

**Pull request closed without merging**
