### PR TITLE
#157

### PR DESCRIPTION
**Pull request by Rouche**

### CODE REVIEW

**Comment by Rouche** [comment]
Oops, build did an automatic commit looks like. And i realised the tabs in code after :(

**Comment by lukepfeiffer10** [comment]
Can you change your commit to only commit the source file changes (don't need to check in the files  under the `dist` folder and you don't need to run the gulp command for increasing the version as I will do that when needed after merging in PRs)? Essentially make a commit with only the changes for `src/mask.js` and I will take care of the rest.


The tests seem to be passing with your change but I haven't had a chance to look at the issue you have and verify this is the right change. I'll try to look into it more soon and hopefully just merge your PR.

**Comment by Rouche** [comment]
Ack im sorry. Just saw your post. I will try removing the dist

**Comment by Rouche** [comment]
Redoing without Dist folder

**Pull request closed without merging**
