### PR TITLE
avoid setting ngModelController to $dirty on initialization.

### PR DESCRIPTION
**Pull request by marbletravis**
I know this can't be merged, and needs some cleanup, (not sure what happened to the min file). But would like to discuss if this can (with cleanup) be merged.

See issues #29 

Travis

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Could you elaborate on why you are not sure if it should be merged ? It seems to be a good idea. Did you forsee compatibility issues or edge cases troubles ?

If you clean up, and add tests I would merge.

**Comment by marbletravis** [comment]
@PowerKiKi My only concern with merging, we getting the ui-mask.js.min.js file name issue resolved in the dist folder. I should have time to resolve that today and update the pull request.

**Comment by PowerKiKi** [comment]
Ok then. If for some reason you can't figure out the dist thing, you can always submit a PR with only the src changed, and I'll take care to build dist when releasing.

Btw, I just updated dev dependencies to latest version, that may help you. I'd suggest you rebase your PR on master and try again...

**Comment by marbletravis** [comment]
@PowerKiKi it looks like the code around initPlaceholder has changed since I made my edits, doesn't look like it would be an issue now that we are not calling eventHandler. I can confirm tomorrow that its not an issue, but I would be surprised if it is. Looks like this pull request might be overcome by events.

```javascript
if (maskProcessed) {
  iElement.val(maskValue(unmaskValue(iElement.val())));
}
```

versus

```javascript
if (maskProcessed) {
   eventHandler({}, true);
}
```

**Comment by marbletravis** [comment]
Closing this pull request, this does not seem to be an issue with the latest code changes.

**Pull request closed without merging**
