### PR TITLE
added index.js

### PR DESCRIPTION
**Pull request by Tim91084**
check out the following:  https://github.com/angular/angular.js/pull/10732

I didn't spend a whole lot of time trying to figure out how you're publishing to npm and bower, but, I think adding this file to whatever you do deploy would add commonjs support.  Just wanted to get this out there.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Could someone confirm that it works as intented, please ?

**Comment by craigcabrey** [comment]
This will work, but `package.json` needs to be updated as well:

`"main": "./dist/index.js"`

**Comment by Tim91084** [comment]
@craigcabrey good point, fixed that.  Should angular be added as a dependency also in package.json?

**Comment by craigcabrey** [comment]
I saw 1.6.4 was published to npm, but I'm not seeing `index.js` added to the package after `npm install`. Do you need to change something in the deploy mechanism to include it in `dist`?

**Comment by Tim91084** [comment]
@craigcabrey this should be good now thanks to  #88

**Comment by PowerKiKi** [comment]
Indeed try the fresh 1.6.5

**Comment by craigcabrey** [comment]
Awesome, I'll give it a whirl. :+1:

**Pull request merged**
