### PR TITLE
Tests and documentation for escChar

### PR DESCRIPTION
**Pull request by isaacplmann**
I added tests and documentation for pull request #73 by @kevingill1966.

All tests are passing.

### CODE REVIEW

**Comment by lukepfeiffer10** [comment]
@isaacplmann Could you remove the changes in the file that are just indentation changes? Also, did you try using the function version of `$apply` and see if that allows for less `\` characters.

i.e.
```javascript
scope.$apply(function() {
    scope.mask = '\\A\\9\\*\\?*';
});
```

This might make the tests easier to read if that option allows you to not double escape everything. I'm assuming the angular expression parser also has the `\` character as an escape which is probably why you had to double the amount used for it to function properly.

**Comment by isaacplmann** [comment]
Yes, putting scope changes in a scope.apply function removed the need for double escaping.  And the indentation changes are no longer part of the pull request.  You might want to fix the spacing on those lines anyway - you have a mix of tabs and spaces.

**Comment by lukepfeiffer10** [comment]
I'll keep it in mind.

Can you squash this into one commit and then I will get this merged.

**Comment by isaacplmann** [comment]
Squashed

**Comment by lukepfeiffer10** [comment]
Thanks!

**Pull request merged**
