### PR TITLE
Fixes how ui-mask sets model value

### PR DESCRIPTION
**Pull request by lu4**
Initially ui-mask sets value out of angular digest cycle which makes all the user-code executed by ng-model $parsers and $filters to run out of angular digest cycle

### CODE REVIEW

**Comment by NickTomlin** [comment]
Could you explain this in a little more detail? From what I understand of [`$setViewValue`](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setViewValue) it will register a change that still goes through the `$parsers` and `$filters`

> When $setViewValue is called, the new value will be staged for committing through the $parsers and $validators pipelines.

But perhaps i'm missing something? A plunkr demonstrating the issue would be really helpful as well. Thanks for bringing this up!

**Comment by lu4** [comment]
On my current project we do validation via custom directive. Our directive requires `ng-model` and in order to subscribe for model changes it injects our validation logic into `ng-model` code via `ng-model` `$parsers` and `$filters`. In response to those model change events we just validate our model and fill an array with validation errors which is later being `ng-repeat`'ed for presentation purposes.

Recently our test team has found-out that validation messages didn't disappear even when model is valid. After detailed inspection I have found out that the model value (an array of errors produced by our validation logic) is empty, however `ng-repeat` over that empty array still produced markup in the browser.

It looked like something was changing that array outside angular's digest cycle. So I debugged deeper down to your library where I've found-out that our code is executed in response to function call on line 425 inside `mask.js`. Line 425 was running in response to jQuery event-handling logic without any angular wrapper in-between.

It means that line 425 `controller.$setViewValue(valUnmasked);` is run directly in response to jQuery event outside digest cycle, and so if `ng-model`'s $parser or $filter will introduce it's own changes to the model, they will be invisible to angular. In simple words `ui-mask` breaks `ng-model` logic by executing it outside $digest loop.

In order to deal with that problem `controller.$setViewValue(valUnmasked);` has to be wrapped by $scope.$apply(...) call...

**Comment by lu4** [comment]
I have found additional problem with `ui-mask` related to `controller.$setViewValue(...)`. When working with `$parsers` and `$filters`, your custom `$parser` will two times:

1) In response to native `ng-model` event subscription
2) In response to subscription done by ui-mask

In first case your custom `$parser` will receive unparsed input with all the `ui-mask` special symbols, the second call will receive a proper input parsed by `ui-mask`

This is all that I can provide, hope this info will help ui-mask to get better...

**Comment by lu4** [comment]
Sorry for closing PR, wrong button... :)

**Comment by NickTomlin** [comment]
Okay, I think this makes sense. I'm trying to think if there are any edge cases we could encounter by delaying the setting of the $viewValue until the next digest cycle. E.g. if the parsers and formatters run, but then we schedule an update that overwrites them. I'll work on recreating this in a Plunkr, but if you could do that work it would be helpful :)

Also, i'm not the maintainer of the project, just someone who is interested in helping out. I don't have the ability to merge this PR in :)

**Comment by lu4** [comment]
It will not cause any delay since currently the execution is done in the void (out of digest cycle), instead it should run the following digest cycle...

**Comment by PowerKiKi** [comment]
@lu4, @NickTomlin you seem to have debugged that thoroughly. I'll trust you on this, since I don't have much time to get more involved with this. Thanks !

**Comment by PowerKiKi** [comment]
When, I said "trust", I meant "merge", not close... my bad :P

**Pull request merged**
