### PR TITLE
maskDefinitions method was missing in configProvider - issue #135

### PR DESCRIPTION
**Pull request by RafaelTaranto**
Completed configProvider tests.

### CODE REVIEW

**Comment by RafaelTaranto** [comment]
I just noticed that the README.md lacks update - "Inside of `ui-options`, you can customize these **four** properties:" should be five properties, located in the Customizing section.

Should i change it and bundle with this PR, make a new PR or let this sort of change for you @lukepfeiffer10?

**Comment by lukepfeiffer10** [comment]
@RafaelTaranto I would say go ahead and change the readme as well if it's just a simple typo like that.

Also, in the config provider when it merges the default object and the new supplied object, have you considered using `angular.merge`. I believe it should do a deep copy/merge like is necessary in this case and should make that function even easier.

**Comment by RafaelTaranto** [comment]
@lukepfeiffer10 the documentation says that every config should be replaced, except for maskDefinitions. If I use angular.merge won't it also merge the eventsToHandle array?

**Comment by lukepfeiffer10** [comment]
@RafaelTaranto I just tested it and you are right about that. It also merges it in an odd way in my opinion. For instance, an array of `[1,2,3]` and an array of `[4]` will be merged using `angular.merge` as `[4,2,3]`.

Best to just leave as is I think then.

**Comment by RafaelTaranto** [comment]
@lukepfeiffer10 okk, just fixed the readme!

**Comment by lukepfeiffer10** [comment]
Thanks!

**Pull request merged**
