### PR TITLE
Improve method unmaskValue, checked if mask has value, before apply it

### PR DESCRIPTION
**Pull request by RenatoRC**
Fixes issue #84

### CODE REVIEW

**Comment by RenatoRC** [comment]
Bug’s reason:
When ng-required is set up, the following code is executed:
 ```javascript
var originalIsEmpty = controller.$isEmpty;
controller.$isEmpty = function(value) {
  if (maskPatterns) {
	return originalIsEmpty(unmaskValue(value || ''));
  } else {
	return originalIsEmpty(value);
  }
};
```

But the conditional "if (maskPatterns)" always is true, because maskPatterns is set to [];
 
When unmaskValue method is executed without mask, always return "", because maskPatternsCopy does not have a value.
```javascript
function unmaskValue(value) {
  var valueUnmasked = '',
				maskPatternsCopy = maskPatterns.slice();
  // Preprocess by stripping mask components from value
  value = value.toString();
 
  angular.forEach(maskComponents, function(component) {
	value = value.replace(component, '');
  });
  angular.forEach(value.split(''), function(chr) {
	if (maskPatternsCopy.length && maskPatternsCopy[0].test(chr)) {
	  valueUnmasked += chr;
	  maskPatternsCopy.shift();
	}
  });
  return valueUnmasked;
}
```
In other places works because before of the call, unmask is checked if the variable maskProcessed is true, but in controller.$isEmpty doesn't check that.
 
 
Solution.
There are many solutions, but I think the best is always unmaskValue check if it has a mask or not.. Before to apply it, like this.
```javascript
// Empty mask, so don't try to apply mask, just return the value
if (maskPatterns.length === 0) {
  return value;
}
```

**Comment by cleever** [comment]
Looks good, thanks!

**Comment by RenatoRC** [comment]
I have another suggestion:

I've created a plunker with your example, because it's best to other people see how the directive works without download the source code.

I suggest that you put it in help page.
http://plnkr.co/edit/egXuGTrDF2UcEja5ITyj?p=preview

**Comment by lukepfeiffer10** [comment]
If you are going to do that you might as well just have the check at the beginning of the function and skip the rest of the code. Since if there are no `maskPatterns`, then there are no `maskComponents` to try and strip either.

Also, why not modify the `$isEmpty` function? That seems like a more logical place to make this change as I don't think `unmaskValue` should even be called unless the `maskPatterns` and/or `maskComponents` arrays have a non zero length.

**Comment by RenatoRC** [comment]
@lukepfeiffer10, I think the best place to put this validation is within the `unmaskValue` method, not `$isEmpty`, Who need to ensure that everything is correct is the method itself, no other

About putting the validation in the first statement... I didn't do that, because I wasn't sure that `maskComponents` don't change other things

Due to this, I tried to explain everything I've done. Feel free to change something.

Regards

**Comment by lukepfeiffer10** [comment]
@RenatoRC I can understand where you are coming from, but what you discovered is actually a bug in the `$isEmpty` function. The only time that the code will hit the `else` block is before `processRawMask` is run for the first time (which happens almost immediately rendering the `else` block mostly useless). This is because the `maskPatterns` variable gets set in the `processRawMask` function to `[]`.

Also, with an empty mask the `processRawMask` function sets `maskProcessed` to `false` which then makes the `initialization` function call `uninitialize`. So, for the case of the `ui-mask` being empty the `ui-mask` code is not initialized. Based on this information I think it would be best to go this route:

```javascript
var originalIsEmpty = controller.$isEmpty;
controller.$isEmpty = function(value) {
  if (maskProcessed) {
    return originalIsEmpty(unmaskValue(value || ''));
  } else {
    return originalIsEmpty(value);
  }
};
```

Ensuring that the `$isEmpty` function knows there has been no mask processed and thus should not call the `unmaskValue` function.

**Comment by RenatoRC** [comment]
@lukepfeiffer10 Yes, There are a bug in `$isEmpty`,

I agreed with your suggest, just to change the variable `maskPatterns` to `maskProcessed`, its works, like this plunker
http://plnkr.co/edit/BoYPUOnjAkfOIeFXS5iP?p=preview


However, there are other way to solve that. We can put the validation inside the `unmaskValue`, just ensure that it'll always works. If someone call them without check if `maskProcess` is true, it will works anyway.
This plunker show up it.
http://plnkr.co/edit/xSeSXGEQhTQJDTjlx7Jx?p=preview

What do you prefer? 

I'm very grateful about your suggest and our discussion here.

**Comment by lukepfeiffer10** [comment]
@RenatoRC My preference is to have the check changed in the `$isEmpty` function because if there is no mask defined then we shouldn't be running the `unmaskValue` function.

If anyone else reads this maybe they have an opinion as well but this seems like the only case where `unmaskValue` is called without a mask being defined and really it shouldn't even be doing that anyway.

**Comment by RenatoRC** [comment]
@lukepfeiffer10 
How I can ignore this pull request?

I'll chang the $isEmpty, how you suggested and do a pull request again. Or maybe, Can you changed the variable and do a new pull request?

**Comment by lukepfeiffer10** [comment]
@RenatoRC I believe you can make the new change and commit on your local branch and then do `git rebase -i HEAD~2` and just delete the previous commit.

This should erase that commit from your local history. Then I think from there you just have to push your branch and the PR should update. However, if you have troubles pushing the local branch do a forced push and it will rewrite the remote branch history to match your local branch.

Hopefully that makes sense... If not I can submit a separate PR later.

**Comment by lukepfeiffer10** [comment]
@RenatoRC Finally got around to making a new PR for this issue #93. Sorry about the delay.

**Comment by RenatoRC** [comment]
@lukepfeiffer10 Thank you very much about new PR.

**Comment by PowerKiKi** [comment]
Merged #93 instead of this one

**Pull request closed without merging**
