### PR TITLE
Placeholder Override

### LINKED ISSUE #4: Mask with placeholder
Using a mask with a placeholder doesn't seem to work properly. For example if I have a phone number mask ``(999) 999-9999`` and a placeholder ``Phone Number`` I get the following result when trying to enter phone number ``123 456 7891``:

``P123e 456b78.``

### PR DESCRIPTION
**Pull request by dimrsilva**
Fix #4

Add test to solution https://github.com/angular-ui/ui-utils/pull/353 given by @qwyzyx.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
The demo is still broken, if I:

1. click on the button ``Set to (999) 999-9999``
2. the first input will show ``(rit) a m-sk o``, but it is expected to show either nothing, or ``(999) 999-9999``

If I modify the demo code to add the new ``ui-mask-placholder`` like so:

````
<input class="form-control" id="masked" name="masked" ui-mask="{{y}}" ng-model="x" placeholder="Write a mask or click a button" ui-mask-placeholder="something">
````

Then I will:

1. click on the button ``Set to (999) 999-9999``
2. give focus to first input
3. first input now show ``(ome) ing-____`` instead of ``something``

While it it is slightly better behavior than without this patch, I am afraid it doesn't really solve the situation.

**Comment by dimrsilva** [comment]
Well, I will change demo.html to work with new feature.

It was implemented this way to not cause backward incompatibly.
When `placeholder` is set, but not `ui-mask-placeholder`, it is used as the mask placeholder.

And about setting `"something"` on `ui-mask-placeholder` and it shows `(ome) ing-____`, it is the correct behaviour, there is no reason to set a `ui-mask-placeholder` that not fits the mask.

**Comment by PowerKiKi** [comment]
If you think breaking BC would allow to give better result, then do it. We'll release as a major version. If an entire rewrite would best suit you, then do it.

**Comment by dimrsilva** [comment]
Indeed, I was thinking on doing some rewrite. Just decouple a service from some methods of the directive.

So, we have a `uiMask` directive, a new `$uiMask` service and a new `uiMask` filter.

I think we can merge this solution now and wait for the refactoring to create a new major version breaking BC.

**Comment by wiltzius** [comment]
So was this closed without merging? I don't see the ui-mask-placeholder attribute on master, but it seems like it would provide a reasonable workaround for issue #4 ?

**Comment by PowerKiKi** [comment]
I never got a chance to merge it, because the branch was deleted. And I believe @dimrsilva is working on a new/better version, possibly entire rewrite of project.

**Comment by wiltzius** [comment]
Gotcha -- @dimrsilva is that so? Otherwise I can reconstruct the addition of the ui-mask-placeholder attribute based on what the pull request did; this is causing problems on our site at the moment so I'm happy to put some effort in.

**Comment by dimrsilva** [comment]
Yes. I reopened the pull request. See #24.

By the way, I am not doing an entire rewrite, just a refactoring of code. I will be able to submit a pull request soon.

**Comment by PowerKiKi** [comment]
Hey @wiltzius, I just released @dimrsilva PR as v1.4.0, you may want to upgrade...

**Comment by wiltzius** [comment]
Thanks!

I've poked around at it a bit and unfortunately I think it still has some funky behavior with placeholders. I might be using it wrong. Should I open issues for the specific use cases that cause surprising behavior?

Thanks,
Tom

**Comment by wiltzius** [comment]
Stuck the examples in https://github.com/angular-ui/ui-mask/issues/25

**Pull request closed without merging**
