### PR TITLE
attempts to fix an issue with modelViewValue, addresses an issue with…

### PR DESCRIPTION
**Pull request by Tim91084**
… extra character input, addresses an issue with passing eventsToHandle in ui-options, fixes test and demo for changes

Model View Value
---
I propose a slight change for the model-view-value implementation.  It shouldn't update the model with a trailing mask.  For example:

for view value (999) 123-123_ X____
model value should be: (999) 123-123

Fix ui-options for eventsToHandle
---
This wasn't working, *I think*, because of a bug in the code.  I made an attempt to fix it.  To summarize the fix, ui-mask was extending the passed in options with the base and eventsToHandle was being overwritten.

Prevent model update on focus when there are no changes being made
---
The event handler was updating the model on focus (by calling setViewValue) even if there was no user input.

Updated demo page and fixed a test
---
I updated the demo page so that you can test model view value and eventsToHandle.

### CODE REVIEW

**Comment by marbletravis** [comment]
@PowerKiKi I think this might be the better approach (at least seems more likely to cover other cases). However I am also not opposed to keeping #51 as well as it will give people the ability to control dirty changes if the value does change (possibly programatically?), not sure.

**Comment by PowerKiKi** [comment]
Trusting @marbletravis opinion on this. @Tim91084 could you rebase the PR please ? then i'll merge

**Comment by Tim91084** [comment]
rebased and moved to #69

**Comment by jeffsheets** [comment]
Wow, good timing, thank you. This commit fixes a bug that I was just about to open that was happening on IE11 when a select box is on the same form.
http://plnkr.co/edit/PPDIiYrcIFY59o5zql9N?p=preview

**Pull request closed without merging**
